const users = {
  'speaker1': {
    jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJqaXRzaSIsInN1YiI6InZpZGVvLWRldi5tZWV0aW5nbWFrZXIuc2UiLCJyb29tIjoic3RhZ2UtMzNjM2MwYTQtNmJjMi00NzlkLTg1YjktNWI2YWZiYjBhODE4IiwiaXNzIjoibWVldGluZ21ha2VyLXdlYi1kZXYiLCJleHAiOjE2MDc3OTU3MjEsImNvbnRleHQiOnsidXNlciI6eyJhdmF0YXIiOiIiLCJuYW1lIjoiMSBTcGVha2VyIiwiZW1haWwiOiJuY2xvbmcuc3BlYWtlci4xQG1haWxpbmF0b3IuY29tIiwiaWQiOiI1OTgifSwiZ3JvdXAiOiIifSwibW9kZXJhdG9yIjpmYWxzZX0.q0sSSymKjdOwg3sjcXiHp9cIkl4QOyOf0h2XZPLdmHQ',
    email: 'nclong.speaker.1@mailinator.com'
  },
  'speaker2': {
    jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJqaXRzaSIsInN1YiI6InZpZGVvLWRldi5tZWV0aW5nbWFrZXIuc2UiLCJyb29tIjoic3RhZ2UtMzNjM2MwYTQtNmJjMi00NzlkLTg1YjktNWI2YWZiYjBhODE4IiwiaXNzIjoibWVldGluZ21ha2VyLXdlYi1kZXYiLCJleHAiOjE2MDc3OTU2MzYsImNvbnRleHQiOnsidXNlciI6eyJhdmF0YXIiOiIiLCJuYW1lIjoiMiBTb2Vha2VyIiwiZW1haWwiOiJuY2xvbmcuc3BlYWtlci4yQG1haWxpbmF0b3IuY29tIiwiaWQiOiI2MzcifSwiZ3JvdXAiOiIifSwibW9kZXJhdG9yIjpmYWxzZX0.ybgZkd5jvMrDlU_3_Jzh_P_3wHk0nhAwi7pJv8qzDI8',
    email: 'nclong.speaker.2@mailinator.com'
  },
}
